### ISSUE TITLE
Legend items overlap on line charts

### ISSUE THREAD

**Issue by joshfriend** [PhilJay/MPAndroidChart#1099]
To reproduce:

1. Draw line chart or combined bar/line chart with no data
2. Add a datapoint
   - Recreate datasets
   - call `chart.setData`
   - call `chart.invalidate`
3. Legend labels overlap as shown below:

![example](https://i.imgur.com/gyvojhV.png)

**Comment by PhilJay** [comment]
This is now fixed.

**Comment by Viperb0y** [comment]
Hey, I am still getting exactly the same error with BarChart. The Legend is not set properly the FIRST time but SECOND button click fixes it. I think it should not happen.
![image](https://user-images.githubusercontent.com/34215978/37233484-ad1693c0-23f3-11e8-9ca8-503445fac79a.png)
But on the second invalidation (button click), same function triggered, same settings, same everything, this happens:
![image](https://user-images.githubusercontent.com/34215978/37233515-ccc79764-23f3-11e8-9bd7-53ba980e05a3.png)
