### ISSUE TITLE
Bug (or feature?) in Cubic Line Chart with setDrawFilled true

### ISSUE THREAD

**Issue by aint** [PhilJay/MPAndroidChart#417]
Hi There!
I played with examples code and found a strange behavior of the  Cubic Line Chart.
When `setDrawCubic` and `setDrawFilled` methods set to `true` the chart filled like this
![screen shot 2015-03-06 at 2 42 18 pm](https://cloud.githubusercontent.com/assets/3179252/6525731/e80a606e-c411-11e4-8e6c-b6d18a188396.png)

But when `setDrawCubic` and `setDrawFilled` methods set to `false` and `true` respectively, all works as expected
![screen shot 2015-03-06 at 2 40 55 pm](https://cloud.githubusercontent.com/assets/3179252/6525687/3337e940-c411-11e4-842a-825d89ecdc29.png)

Of course this happens only when the chart entries added with `xIndex` offset
```
for (int i = 0; i < count; i++) {
            vals1.add(new Entry(val, i + 5));
        }
```
Thanks in before.

**Comment by PhilJay** [comment]
Thanks for letting me know, I will check it out. Looks like a bug to me.

**Comment by PhilJay** [comment]
Should be fixed now.

**Comment by inneke-dc** [comment]
I'm still seeing this issue.
![chart fill](https://cloud.githubusercontent.com/assets/11866704/12296184/6437422a-ba06-11e5-8f3c-8dbb518f919d.PNG)
Is there any way to fix this?

**Comment by PhilJay** [comment]
Library version?

**Comment by inneke-dc** [comment]
@PhilJay Version 2.1.6

**Comment by inneke-dc** [comment]
This only happens if I don't specify an entry for every xValue. For example if the xVals list contains 4 items:

    List<String> xVals = new ArrayList<>();
    xVals.add("A");
    xVals.add("B");
    xVals.add("C");
    xVals.add("D");
    return new LineData(xVals, dataSets);

Then this will work:

        entries.add(new Entry(130, 0));
        entries.add(new Entry(150, 1));
        entries.add(new Entry(120, 2));
        entries.add(new Entry(70, 3));

But this won't:

        entries.add(new Entry(130, 0));
        entries.add(new Entry(150, 1));
        //entries.add(new Entry(120, 2));
        entries.add(new Entry(70, 3));
