### ISSUE TITLE
BarChart setStartAtZero not working?

### ISSUE THREAD

**Issue by svasic** [PhilJay/MPAndroidChart#475]
I'm not sure if I understand behaviour of setStartAtZero(...)
I have a bar chart where some of the values on xIndexes are 0. If I call setStartAtZero(false) for YAxis, i expect to see small stack (like 10dp offset) on X indexes where value is 0, but it's not working like that.   Nothing happens if I set startAtZero to false ... stacks are not drawn for 0 values. 

Can I achieve this behaviour via library? Currently I'm using ugly workaround for this feature and adding some extra space to BarBuffer top value.

**Comment by PhilJay** [comment]
Is this related to issue #409 ?

If so, it should be fixed now.

**Comment by svasic** [comment]
I tried it and it does not fix our issue. For better understanding here is some more details:
In BarChart I have 6 categories (XAxis values). Data for BarChart is like this: [0, 100], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0]
Because i dont want to have empty stack on 1,2,3,4,5 categories, I use setStartAtZero(false) in combination with yAxis.setAxisMinValue(X); where X is the minimum bottom offset i want to see on every stack.
This is the output i would like to achieve
![image](https://cloud.githubusercontent.com/assets/9920953/6865144/35177270-d46b-11e4-9f8a-6dacab3d2b7b.png)

Instead of this i get:
![image](https://cloud.githubusercontent.com/assets/9920953/6865174/6e4ba12e-d46b-11e4-9948-9c2af00604d4.png)

There are two issues here:
- first is that i dont see bottom rectangle that should appear when setting setStartAtZero(false)
- and the second is that if I call setAxisMinValue(X), then I don't see zero values  (Y value) above 1,2,3,4,5 (X values) - obviously because they are filtered out, based on axis min value which is used for different purposes. There should be method for setting minOffsetFromAxis which doesn't have impact on the data filtration.

I hope its clear now, what our use case is, and hopefully this can be fixed. As i said, i'm using ugly workaround, which will certainly give me headaches in the future if i don't remove it asap :)

thank you
