### ISSUE TITLE
Pie chart animation trasparent circle radius

### ISSUE THREAD

**Issue by Blodgard** [PhilJay/MPAndroidChart#543]
![screenshot_2015-04-12-13-16-33](https://cloud.githubusercontent.com/assets/11709402/7105388/69b51caa-e116-11e4-97f1-e059653973e6.png)

In the new version this bug appears.
The transparent circle radius is drawed immediately.

**Comment by PhilJay** [comment]
The little change I just made should fix this, please try.

**Comment by Blodgard** [comment]
Yes thanks this partially solved the issue.
However now the transparent circle is drawed at the end of the animation.
It's not possible to draw at the same time like in the previous version?
In the previous version the effect was really better.
