### ISSUE TITLE
LineChart.fitScreen()  not working as expected after calling setVisibleXRange 

### ISSUE THREAD

**Issue by SjoerdvGestel** [PhilJay/MPAndroidChart#625]
Hi,

I use one graph to render different datasets with different intervals. 
The first time i render a dataset with only 3 points, so i let the graph fill the screen, 
now i render a new set witch has 12 points, i set setVisibleXRange to 6 and now i can scroll,
now i set the previous dataset back, and call fitScreen(), this now does not work as expected, cause it will take the 3 datapoints and uses not the screen with as i would expect, but the previous width of the graph.

i call clear() and invalidate() when needed.

Any idea how to reset the graph so it will take screen with when i ask it to?

**Comment by PhilJay** [comment]
Sorry, I don't understand. What do you mean by "the previous with"?

**Comment by SjoerdvGestel** [comment]
Sorry it was a typo, should have said width. 

The second time i render a dataset (12 points) in the graph, the witdh is about 2.5 time the screen with by setting setVisibleXRange  to 6, when i then render 3 datapoints after that, even if i call fitScreen() it will use the witdh previously used by the 12 datapoints. making the spaces between the pints extremely big. 

af of my understanding of the graph... fitScreen() would reset this to fit the screen again.. but the matrix behind it all is set to another size and will be used. there is no clean way of resetting this. Or if there is.. i haven't found it.

**Comment by SjoerdvGestel** [comment]
![1](https://cloud.githubusercontent.com/assets/1597644/7532909/a37d6040-f56c-11e4-99d0-d1afd22f752d.png)
![2](https://cloud.githubusercontent.com/assets/1597644/7532911/a37ecc32-f56c-11e4-9171-ae08872e6c9b.png)
![3](https://cloud.githubusercontent.com/assets/1597644/7532910/a37d87d2-f56c-11e4-8ae5-39555938d24e.png)

**Comment by SjoerdvGestel** [comment]
@PhilJay did you have a look at the updated explanation? I would like to know your view on the issue.

**Comment by SjoerdvGestel** [comment]
@PhilJay Hi! Could you tell me if this has been fixed, or if there's a workaround for it or something.

**Comment by PhilJay** [comment]
I just pushed a "maybe" fix, please try again and let me know :-)

**Comment by olivierg13** [comment]
Hello @PhilJay 
I'm affected by the same problem. Could you give a try at @OleksandrDudinskyi/MPAndroidChart commit?
I use setVisibleXRange(number of entries) as a temporary fix right now, instead of calling fitScreen().

**Comment by grajadurai** [comment]
I have the same issue. Calling the fitScreen() method inside a Handler seems to work sometimes, but not always. Also, setVisibleXRange() did not fix the issue as well.

**Comment by RuchiteshPM** [comment]
I have a button which executes the lineChart.fitScreen() after clicking on it. But when I scroll and click on button immediately nothing happens. How can I provide more priority to fitScreen() method over scrolling effect ??

**Comment by vad-zuev** [comment]
Same issue as @Rpmalukani22 describes. Is there any way to stop/cancel the scroll and zoom out immediately after `fitScreen()` is called?

**Comment by recoverrelax** [comment]
Attempted workaround for fitScreen while dragging:

```
fun resetScreen() {
        // we need this 'trick' to stop drag before fitScreen
        // otherwise fitScreen won't work
        chart.dragDecelerationFrictionCoef = 0f

        chart.post {
            combinedChart.fitScreen()
            chart.post {
                combinedChart.dragDecelerationFrictionCoef = 1f
            }
        }
    }
```

**Comment by marticztn** [comment]
> Attempted workaround for fitScreen while dragging:
> 
> ```
> fun resetScreen() {
>         // we need this 'trick' to stop drag before fitScreen
>         // otherwise fitScreen won't work
>         chart.dragDecelerationFrictionCoef = 0f
> 
>         chart.post {
>             combinedChart.fitScreen()
>             chart.post {
>                 combinedChart.dragDecelerationFrictionCoef = 1f
>             }
>         }
>     }
> ```

Thank you! This worked!
